apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicin-db
  namespace: musicin
  labels:
    app: musicin-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicin-db
      tier: database
  template:
    metadata:
      labels:
        app: musicin-db
        tier: database
    spec:
      volumes:
        - name: musicindb-volume
          persistentVolumeClaim:
            claimName: musicindb-pvc
      containers:
        - name: musicin-db
          image: olddriverua/database:latest
          ports:
            - containerPort: 3306
              name: musicin-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: musicin
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: musicindb-volume

